name: Build

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Build application
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Setup
        run: |
          pwd
          bundle install
          bundle exec fastlane setup_ci force:true

      - name: Run fastlane lane
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          WORKSPACE: MyApp.xcworkspace
        run: bundle exec fastlane build
