name: Pull Requests

on:
  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          bundle install

      - name: Run fastlane lane
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          WORKSPACE: MyApp.xcworkspace
        run: bundle exec fastlane test
